# Generated by Django 5.0.6 on 2024-10-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('teacher', 'Teacher'), ('admin', 'Admin')], db_index=True, default='admin', max_length=15),
        ),
    ]
