# Generated by Django 5.0.6 on 2024-11-22 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_geofence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geofence',
            name='office_lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='geofence',
            name='office_long',
            field=models.FloatField(),
        ),
    ]
