# Generated by Django 5.0.6 on 2024-11-23 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_geofence_office_lat_alter_geofence_office_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geofence',
            name='geofence_radius',
            field=models.FloatField(),
        ),
    ]
